Repository eternagame/eterna-next, pull requests merged in 2022-12, with the labels that each got.

#20 chore(repo): Fix actions cache keys
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: type: ergonomics, size: xs, scope: repo

#19 chore(repo): Create CODEOWNERS
  .github/CODEOWNERS
Labels: type: ergonomics, scope: repo

#301 chore(repo): Add new scopes to PR lint
  .github/workflows/pr-lint.yml
Labels: type: ergonomics, size: sm, scope: repo

#300 feat(design-system): Initialize design tokens
  package-lock.json
  package.json
  packages/design-system/token-transformer/LICENSE
  packages/design-system/token-transformer/README.md
  packages/design-system/token-transformer/index.ts
  packages/design-system/token-transformer/package.json
  packages/design-system/token-transformer/src/__tests__/lib.spec.ts
  packages/design-system/token-transformer/src/lib.ts
  packages/design-system/token-transformer/tsconfig.build.json
  packages/design-system/token-transformer/tsconfig.json
  packages/design-system/token-transformer/tsconfig.spec.json
  packages/design-system/token-transformer/vite.config.ts
  packages/design-system/tokens/README.md
  packages/design-system/tokens/package.json
  packages/design-system/tokens/tokens.json
  release-please-config.json
Labels: scope: design-system, type: design
